repos:
  - repo: https://github.com/prettier/prettier.git
    rev: 1.19.1
    hooks:
      - id: prettier
        args: [--single-quote]
        exclude: package-lock.json
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
        args: [--maxkb=3000]
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
  #  - repo: https://github.com/pre-commit/mirrors-scss-lint
  #    rev: v0.59.0
  #    hooks:
  #      - id: scss-lint
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.1
    hooks:
      - id: git-check
      - id: markdownlint
        args: [-r, '~MD013,~MD004']
      - id: require-ascii
        exclude: calculator
      - id: shellcheck
  - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.0
    hooks:
      - id: dockerfile_lint
      - id: markdown-toc
      - id: htmlhint
        args: [--config, .htmlhintrc]
      - id: htmllint
        exclude: |
          (?x)(
              ^public/|
              ^calculator/
          )
  - repo: https://github.com/Lucas-C/pre-commit-hooks-java
    rev: 1.3.9
    hooks:
      - id: validate-html
        exclude: |
          (?x)(
              ^public/|
              ^calculator/
          )
  - repo: https://github.com/jstewmon/check-swagger
    rev: v0.1.4
    hooks:
      - id: check-swagger
  - repo: https://github.com/lovesegfault/beautysh.git
    rev: 6.0.1
    hooks:
      - id: beautysh
