linters:
  ColorKeyword:
    enabled: true
  EmptyLineBetweenBlocks:
    enabled: false
  ColorVariable:
    enabled: false
  Comment:
    enabled: true
  HexLength:
    enabled: true
  IdSelector:
    enabled: true
  ImportPath:
    enabled: true
  Indentation:
    enabled: true
  LeadingZero:
    enabled: false
  VendorPrefix:
    enabled: false
  MergeableSelector:
    enabled: false
  NestingDepth:
    enabled: false
  SelectorDepth:
    enabled: false
  PseudoElement:
    enabled: false
  SingleLinePerSelector:
    enabled: false
  NameFormat:
    enabled: false
  PropertySortOrder:
    enabled: false
  SelectorFormat:
    enabled: false
  SpaceAfterPropertyColon:
    enabled: true
  SpaceBeforeBrace:
    enabled: true
  StringQuotes:
    enabled: true
  TrailingSemicolon:
    enabled: true
